import {
    CalendarDays,
    BadgeDollarSign,
    MessageSquareText,
    Users,
    BriefcaseBusiness,
    ShoppingCart,
    ReceiptText,
    UserRoundCog,
    Award,
    ChartColumn,
    Settings,
} from "lucide-react";

export const sidebarSections = [
    {
        type: "item",
        id: "agenda",
        label: "Agenda",
        icon: CalendarDays,
        visible: true,
    },
    {
        type: "item",
        id: "outstanding",
        label: "Cobranças",
        icon: BadgeDollarSign,
        visible: true,
    },
    {
        type: "group",
        id: "group_items",
        label: "Itens",
        visible: true,
    },
    {
        type: "item",
        id: "mpd",
        label: "Msgs Pré-definidas",
        icon: MessageSquareText,
        visible: true,
    },
    {
        type: "item",
        id: "customers",
        label: "Clientes",
        icon: Users,
        visible: true,
    },
    {
        type: "item",
        id: "services",
        label: "Serviço",
        icon: BriefcaseBusiness,
        visible: true,
    },
    {
        type: "item",
        id: "products",
        label: "Produtos e Estoque",
        icon: ShoppingCart,
        visible: false,
    },
    {
        type: "item",
        id: "expenses",
        label: "Despesas",
        icon: ReceiptText,
        visible: true,
    },
    {
        type: "item",
        id: "employees",
        label: "Funcionários",
        icon: UserRoundCog,
        visible: false,
    },
    {
        type: "item",
        id: "entitlements",
        label: "Assinaturas",
        icon: BadgeDollarSign,
        visible: true,
    },
    {
        type: "group",
        id: "group_reports",
        label: "Relatórios",
        visible: true,
    },
    {
        type: "item",
        id: "top_customers",
        label: "Melhores clientes",
        icon: Award,
        visible: true,
    },
    {
        type: "item",
        id: "overview",
        label: "Resumo financeiro",
        icon: ChartColumn,
        visible: true,
    },
    {
        type: "group",
        id: "group_account",
        label: "Conta",
        visible: true,
    },
    {
        type: "item",
        id: "settings",
        label: "Minha conta",
        icon: Settings,
        visible: true,
    }
];

export const sidebarTranslate = {
    agenda: "Agenda",
    outstanding: "Cobranças",
    mpd: "Msgs Pré-definidas",
    customers: "Clientes",
    services: "Serviço",
    products: "Produtos e Estoque",
    expenses: "Despesas",
    employees: "Funcionários",
    top_customers: "Melhores clientes",
    overview: "Resumo financeiro",
    settings: "Minha conta",
    logout: "Sair",
    home: "Página inicial",
};
